
# Site settings
title: Jinay Shah
email: jinay.sh99@gmail.com
description: Software Engineer / ML Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jinayshah7.github.io/" # the base hostname & protocol for your site
# youtube_username: jinayshah
github_username:  jinayshah7
paginate: 50
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
